module.exports = {
  plugins: ["stylelint-order", "stylelint-declaration-use-variable", "stylelint-prettier"],
  rules: {
    "prettier/prettier": true,
    "declaration-block-no-duplicate-properties": true,
    "declaration-no-important": true,
    "color-no-invalid-hex": true,
    "color-hex-length": "short",
    "max-nesting-depth": 6,
    "selector-pseudo-element-colon-notation": "double",
    "declaration-block-no-shorthand-property-overrides": true,
    "length-zero-no-unit": true,
    "unit-whitelist": [
      ["px", "%", "s", "vh", "deg"],
      {
        ignoreProperties: {
          "px": ["border", "width", "height", "margin", "top"],
          "%": ["width", "height", "top"],
          "vh": ["width", "height"],
          "vw": ["width", "height"],
          "vmin": ["width", "height"],
          "vmax": ["width", "height"],
          "em": ["top"],
          "rem": ["margin"],
          "deg": ["transform"]
        }
      }
    ],
    "function-linear-gradient-no-nonstandard-direction": true,
    "order/properties-order": [
      "position",
      "top",
      "right",
      "bottom",
      "left",
      "z-index",
      "display",
      "align-content",
      "align-items",
      "align-self",
      "flex",
      "flex-basis",
      "flex-direction",
      "flex-flow",
      "flex-grow",
      "flex-shrink",
      "flex-wrap",
      "justify-content",
      "order",
      "float",
      "width",
      "height",
      "max-width",
      "max-height",
      "min-width",
      "min-height",
      "padding",
      "padding-top",
      "padding-right",
      "padding-bottom",
      "padding-left",
      "margin",
      "margin-top",
      "margin-right",
      "margin-bottom",
      "margin-left",
      "margin-collapse",
      "margin-top-collapse",
      "margin-right-collapse",
      "margin-bottom-collapse",
      "margin-left-collapse",
      "overflow",
      "overflow-x",
      "overflow-y",
      "clip",
      "clear",
      "font",
      "font-family",
      "font-size",
      "font-smoothing",
      "osx-font-smoothing",
      "font-style",
      "font-weight",
      "hyphens",
      "src",
      "line-height",
      "letter-spacing",
      "word-spacing",
      "color",
      "text-align",
      "text-decoration",
      "text-indent",
      "text-overflow",
      "text-rendering",
      "text-size-adjust",
      "text-shadow",
      "text-transform",
      "word-break",
      "word-wrap",
      "white-space",
      "vertical-align",
      "list-style",
      "list-style-type",
      "list-style-position",
      "list-style-image",
      "pointer-events",
      "cursor",
      "background",
      "background-attachment",
      "background-color",
      "background-image",
      "background-position",
      "background-repeat",
      "background-size",
      "border",
      "border-collapse",
      "border-top",
      "border-right",
      "border-bottom",
      "border-left",
      "border-color",
      "border-image",
      "border-top-color",
      "border-right-color",
      "border-bottom-color",
      "border-left-color",
      "border-spacing",
      "border-style",
      "border-top-style",
      "border-right-style",
      "border-bottom-style",
      "border-left-style",
      "border-width",
      "border-top-width",
      "border-right-width",
      "border-bottom-width",
      "border-left-width",
      "border-radius",
      "border-top-right-radius",
      "border-bottom-right-radius",
      "border-bottom-left-radius",
      "border-top-left-radius",
      "border-radius-topright",
      "border-radius-bottomright",
      "border-radius-bottomleft",
      "border-radius-topleft",
      "content",
      "quotes",
      "outline",
      "outline-offset",
      "outline-width",
      "outline-style",
      "outline-color",
      "opacity",
      "filter",
      "visibility",
      "size",
      "zoom",
      "transform",
      "box-align",
      "box-flex",
      "box-orient",
      "box-pack",
      "box-shadow",
      "box-sizing",
      "table-layout",
      "animation",
      "animation-delay",
      "animation-duration",
      "animation-iteration-count",
      "animation-name",
      "animation-play-state",
      "animation-timing-function",
      "animation-fill-mode",
      "transition",
      "transition-delay",
      "transition-duration",
      "transition-property",
      "transition-timing-function",
      "background-clip",
      "backface-visibility",
      "resize",
      "appearance",
      "user-select",
      "interpolation-mode",
      "direction",
      "marks",
      "page",
      "set-link-source",
      "unicode-bidi",
      "speak"
    ],
    "sh-waqar/declaration-use-variable": [
      [
        "/color/",
        "font",
        {
          ignoreValues: ["transparent", "inherit", "initial", "unset"]
        }
      ]
    ],

    // Pattern for our implementation of hyphenated_BEM
    // https://github.com/bjankord/stylelint-config-sass-guidelines/issues/20#issuecomment-349972873
    "selector-class-pattern": [
      "^(?:(?:hs)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?$",
      {
        severity: "warning"
      }
    ],

    // Disallow vendor prefixes
    "property-no-vendor-prefix": [
      true,
      {
        severity: "warning"
      }
    ],
    "value-no-vendor-prefix": true,
    "selector-no-vendor-prefix": [
      true,
      {
        severity: "warning"
      }
    ],
    "at-rule-no-vendor-prefix": true,
    "media-feature-name-no-vendor-prefix": [
      true,
      {
        severity: "warning"
      }
    ],

    // Disallow unknown properties, values etc.
    "property-no-unknown": true,
    "unit-no-unknown": true,
    "selector-type-no-unknown": true,
    "selector-pseudo-class-no-unknown": true,
    "selector-pseudo-element-no-unknown": true,
    "media-feature-name-no-unknown": [
      true,
      {
        severity: "warning"
      }
    ],
    "no-unknown-animations": true
  }
};
